### ISSUE TITLE
Some Code Package Missing 【Help wanted】

### ISSUE THREAD

**Issue by zw-SIMM** [microsoft/syntheseus#55] opened 2024-01-08 03:18 UTC
When running the scripts
```
from syntheseus.reaction_prediction.inference import *

models = [
    LocalRetroModel(),
]
```

Meet errors

```
ImportError: cannot import name 'scripts' from 'local_retro' (/home/zw/syntheseus/syntheseus/reaction_prediction/inference/local_retro.py)
```

When running the scripts
```
from syntheseus.reaction_prediction.inference import *

models = [
    RootAlignedModel(),
]
```
Meet errors
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)

ImportError: cannot import name 'score' from 'root_aligned' (/home/zw/syntheseus/syntheseus/reaction_prediction/inference/root_aligned.py)
```

**Comment by AustinT** [comment] 2024-01-08 17:24
Hello @zw-SIMM, thanks for your interest in syntheseus.

I tried to reproduce your issue by creating a fresh conda environment, cloning syntheseus, running `pip install ".[all]"`, then running the lines of code in your issue. They ran without generating any error for me.

Without any more information on your setup I don't think I can help. Try re-installing your environment? If it still does not work, please provide instructions to create a python environment where this error is reproduced and we can try to help.

**Comment by zw-SIMM** [comment] 2024-01-09 00:45
> Hello @zw-SIMM, thanks for your interest in syntheseus.
> 
> I tried to reproduce your issue by creating a fresh conda environment, cloning syntheseus, running , then running the lines of code in your issue. They ran without generating any error for me.`pip install ".[all]"`
> 
> Without any more information on your setup I don't think I can help. Try re-installing your python environment? If it still does not work, please provide instructions to create a python environment where this error is reproduced and we can try to help.

Thanks a lot for your reply!
I re-installed my python environment and it worked. ✌
```
mamba env create -f environment.yml
mamba activate syntheseus
pip install -e ".[local-retro,root-aligned]"
```

Another question, when I tried to run,
```
pip install ".[all]"
```
met errors (maybe due to my 12.3 cuda version?)
```
/home/zw/miniforge-pypy3/envs/syntheseus-full/lib/python3.9/site-packages/torch/include/ATen/core/builtin_function.h(117): warning #20236-D: pragma "diag_default" is deprecated, use "nv_diag_default" instead
      
      /usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
        435 |         function(_Functor&& __f)
            |                                                                                                                                                 ^
      /usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
      /usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
        530 |         operator=(_Functor&& __f)
            |                                                                                                                                                  ^
      /usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
      error: command '/usr/bin/nvcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter
Successfully built syntheseus
Failed to build torch-scatter
ERROR: Could not build wheels for torch-scatter, which is required to install pyproject.toml-based projects
```

**Comment by AustinT** [comment] 2024-01-09 09:52
Glad to hear that this worked for you! I will close this issue.


> Another question, when I tried to run,
> 
> ```
> pip install ".[all]"
> ```
> 
> met errors (maybe due to my 12.3 cuda version?)
> 
> ```
> /home/zw/miniforge-pypy3/envs/syntheseus-full/lib/python3.9/site-packages/torch/include/ATen/core/builtin_function.h(117): warning #20236-D: pragma "diag_default" is deprecated, use "nv_diag_default" instead
>       
>       /usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
>         435 |         function(_Functor&& __f)
>             |                                                                                                                                                 ^
>       /usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
>       /usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
>         530 |         operator=(_Functor&& __f)
>             |                                                                                                                                                  ^
>       /usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
>       error: command '/usr/bin/nvcc' failed with exit code 1
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for torch-scatter
>   Running setup.py clean for torch-scatter
> Successfully built syntheseus
> Failed to build torch-scatter
> ERROR: Could not build wheels for torch-scatter, which is required to install pyproject.toml-based projects
> ```

This looks like an issue with CUDA or g++. I found a similar issue on [stackoverflow](https://stackoverflow.com/questions/74350584/nvcc-compilation-error-using-thrust-in-cuda-11-5), although it is for a different CUDA version. This is not an issue with syntheseus though (the error seems to come from the installation of `torch-scatter`), so we are not the right people to help you with it. Hope you are able to resolve it!

**Closed by AustinT** 2024-01-09 09:52 UTC
